export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const FIELD_CHANGE = 'FIELD_CHANGE'
export const SET_AMOUNT = 'SET_AMOUNT'
export const SET_TERM = 'SET_TERM'
export const SET_RATE = 'SET_RATE'
export const ADD_LOAN = 'ADD_LOAN'
export const EDIT_LOAN = 'EDIT_LOAN'
export const DELETE_LOAN = 'DELETE_LOAN'
